export interface KBEntry {
  id: string;
  category: string;
  subCategory: string;
  question: string;
  answer: string;
  keywords: string[];
  disclaimer: boolean;
}

export const getInitialKBData = (): KBEntry[] => [
  // 🟢 A. SALUTATIONS SIMPLES
  {
    id: 'S1_01',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S1_salutations',
    question: 'Bonjour',
    answer: 'Bonjour 👋 Bienvenue sur Nye Cyclea, ton assistante virtuelle de santé féminine.',
    keywords: ['bonjour', 'coucou', 'hello', 'cc', 'bjr'],
    disclaimer: false,
  },
  {
    id: 'S1_02',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S1_salutations',
    question: 'Salut',
    answer: 'Salut 😊 Je suis le chatbot de Nye Cyclea. Comment puis-je t’aider ?',
    keywords: ['salut', 'slt'],
    disclaimer: false,
  },
  {
    id: 'S1_03',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S1_salutations',
    question: 'Hello',
    answer: 'Hello 👋 Je suis l’assistante virtuelle de Nye Cyclea.',
    keywords: ['hello'],
    disclaimer: false,
  },
  {
    id: 'S1_04',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S1_salutations',
    question: 'Coucou',
    answer: 'Coucou 😊 Je suis là pour t’accompagner sur la santé féminine.',
    keywords: ['coucou', 'cc'],
    disclaimer: false,
  },
  {
    id: 'S1_05',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S1_salutations',
    question: 'Bonsoir',
    answer: 'Bonsoir 🌙 Je suis le chatbot de Nye Cyclea. Tu peux me poser une question.',
    keywords: ['bonsoir', 'bsr'],
    disclaimer: false,
  },
  {
    id: 'S1_06',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S1_salutations',
    question: 'Hey',
    answer: 'Hey 👋 Je suis prête à répondre à tes questions sur le cycle menstruel.',
    keywords: ['hey'],
    disclaimer: false,
  },
  {
    id: 'S1_07',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S1_salutations',
    question: 'Allô',
    answer: 'Allô 😊 Oui, je suis là.',
    keywords: ['allo'],
    disclaimer: false,
  },
  {
    id: 'S1_08',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S1_salutations',
    question: 'Il y a quelqu’un ?',
    answer: 'Oui 👍 Je suis l’assistante virtuelle de Nye Cyclea.',
    keywords: ['quelquun', 'la'],
    disclaimer: false,
  },
  {
    id: 'S1_09',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S1_salutations',
    question: 'Salut Nye Cyclea',
    answer: 'Salut 👋 Bienvenue sur Nye Cyclea.',
    keywords: ['salut', 'nye'],
    disclaimer: false,
  },
  {
    id: 'S1_10',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S1_salutations',
    question: 'Bonjour chatbot',
    answer: 'Bonjour 😊 Je suis le chatbot officiel de Nye Cyclea.',
    keywords: ['bonjour', 'chatbot'],
    disclaimer: false,
  },
  {
    id: 'S1_11',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S1_salutations',
    question: 'Yo',
    answer: 'Yo 👋 Je suis là pour t’aider.',
    keywords: ['yo'],
    disclaimer: false,
  },
  {
    id: 'S1_12',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S1_salutations',
    question: 'Ça va ?',
    answer: 'Merci 😊 Je vais bien. Comment puis-je t’aider ?',
    keywords: ['ca', 'va', 'bien', 'comment', 'vas', 'tu'],
    disclaimer: false,
  },
  {
    id: 'S1_13',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S1_salutations',
    question: 'Salut ça va ?',
    answer: 'Oui 😊 Je suis prête à t’aider.',
    keywords: ['salut', 'va'],
    disclaimer: false,
  },
  {
    id: 'S1_14',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S1_salutations',
    question: 'Bonsoir Nye Cyclea',
    answer: 'Bonsoir 🌙 Bienvenue sur Nye Cyclea.',
    keywords: ['bonsoir', 'nye'],
    disclaimer: false,
  },
  {
    id: 'S1_15',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S1_salutations',
    question: 'Bonjour assistante',
    answer: 'Bonjour 👋 Je suis l’assistante virtuelle de Nye Cyclea.',
    keywords: ['bonjour', 'assistante'],
    disclaimer: false,
  },
  {
    id: 'S1_16',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S1_salutations',
    question: 'Hey bot',
    answer: 'Hey 😊 Je suis le chatbot de Nye Cyclea.',
    keywords: ['hey', 'bot'],
    disclaimer: false,
  },
  {
    id: 'S1_17',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S1_salutations',
    question: 'Salut bot',
    answer: 'Salut 👋 Comment puis-je t’aider aujourd’hui ?',
    keywords: ['salut', 'bot'],
    disclaimer: false,
  },
  {
    id: 'S1_18',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S1_salutations',
    question: 'Bonjour intelligence artificielle',
    answer: 'Bonjour 👋 Je suis une assistante virtuelle intégrée à Nye Cyclea.',
    keywords: ['bonjour', 'ia', 'intelligence'],
    disclaimer: false,
  },
  {
    id: 'S1_19',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S1_salutations',
    question: 'Hello bot',
    answer: 'Hello 😊 Je suis là pour t’informer.',
    keywords: ['hello', 'bot'],
    disclaimer: false,
  },
  {
    id: 'S1_20',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S1_salutations',
    question: 'Bonsoir chatbot',
    answer: 'Bonsoir 🌙 Pose-moi ta question.',
    keywords: ['bonsoir', 'chatbot'],
    disclaimer: false,
  },
  {
    id: 'S1_21',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S1_salutations',
    question: 'Coucou Nye Cyclea',
    answer: 'Coucou 😊 Je suis là pour toi.',
    keywords: ['coucou', 'nye'],
    disclaimer: false,
  },
  {
    id: 'S1_22',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S1_salutations',
    question: 'Bonjour madame',
    answer: 'Bonjour 👋 Je suis une assistante virtuelle, pas une personne réelle.',
    keywords: ['bonjour', 'madame'],
    disclaimer: false,
  },
  {
    id: 'S1_23',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S1_salutations',
    question: 'Hey Nye',
    answer: 'Hey 😊 Bienvenue sur Nye Cyclea.',
    keywords: ['hey', 'nye'],
    disclaimer: false,
  },
  {
    id: 'S1_24',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S1_salutations',
    question: 'Salut assistant',
    answer: 'Salut 👋 Je suis à ton écoute.',
    keywords: ['salut', 'assistant'],
    disclaimer: false,
  },
  {
    id: 'S1_25',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S1_salutations',
    question: 'Bonjour tout le monde',
    answer: 'Bonjour 👋 Je suis l’assistante virtuelle de Nye Cyclea.',
    keywords: ['bonjour', 'monde'],
    disclaimer: false,
  },

  // 🟡 B. IDENTITÉ DU CHATBOT
  {
    id: 'S2_01',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S2_identity',
    question: 'Qui es-tu ?',
    answer: 'Je suis le chatbot de Nye Cyclea, une application dédiée à la santé féminine.',
    keywords: ['qui', 'es', 'tu'],
    disclaimer: false,
  },
  {
    id: 'S2_02',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S2_identity',
    question: 'Tu es qui ?',
    answer: 'Je suis une assistante virtuelle de santé féminine.',
    keywords: ['qui'],
    disclaimer: false,
  },
  {
    id: 'S2_03',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S2_identity',
    question: 'Quel est ton nom ?',
    answer: 'Je suis le chatbot de Nye Cyclea.',
    keywords: ['nom', 'appelles'],
    disclaimer: false,
  },
  {
    id: 'S2_04',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S2_identity',
    question: 'Tu es humaine ?',
    answer: 'Non 😊 Je suis un assistant virtuel automatisé.',
    keywords: ['humaine', 'femme'],
    disclaimer: false,
  },
  {
    id: 'S2_05',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S2_identity',
    question: 'Tu es un robot ?',
    answer: 'Oui 🤖 Je suis un chatbot conçu pour informer.',
    keywords: ['robot', 'bot'],
    disclaimer: false,
  },
  {
    id: 'S2_06',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S2_identity',
    question: 'Tu es une IA ?',
    answer: 'Oui. Je suis une intelligence artificielle intégrée à Nye Cyclea.',
    keywords: ['ia', 'intelligence'],
    disclaimer: false,
  },
  {
    id: 'S2_07',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S2_identity',
    question: 'Tu travailles pour qui ?',
    answer: 'Je fais partie de l’application Nye Cyclea.',
    keywords: ['travailles', 'pour', 'qui'],
    disclaimer: false,
  },
  {
    id: 'S2_08',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S2_identity',
    question: 'Tu es réelle ?',
    answer: 'Je suis virtuelle, mais conçue pour être utile.',
    keywords: ['reelle', 'vrai'],
    disclaimer: false,
  },
  {
    id: 'S2_09',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S2_identity',
    question: 'Tu es une femme ?',
    answer: 'Non. Je n’ai pas de genre. Je suis une assistante virtuelle.',
    keywords: ['femme', 'genre'],
    disclaimer: false,
  },
  {
    id: 'S2_10',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S2_identity',
    question: 'Tu es un médecin ?',
    answer: 'Non ❌ Je ne suis pas médecin.',
    keywords: ['medecin', 'docteur'],
    disclaimer: true,
  },
  {
    id: 'S2_11',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S2_identity',
    question: 'Tu es une sage-femme ?',
    answer: 'Non ❌ Je fournis seulement des informations générales.',
    keywords: ['sage', 'femme'],
    disclaimer: false,
  },
  {
    id: 'S2_12',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S2_identity',
    question: 'Tu es fiable ?',
    answer: 'Je fournis des informations éducatives fiables, mais générales.',
    keywords: ['fiable', 'confiance'],
    disclaimer: false,
  },
  {
    id: 'S2_13',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S2_identity',
    question: 'Tu es là pour quoi ?',
    answer: 'Pour informer et accompagner sur la santé féminine.',
    keywords: ['quoi', 'sert'],
    disclaimer: false,
  },
  {
    id: 'S2_14',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S2_identity',
    question: 'Pourquoi tu existes ?',
    answer: 'Pour aider les femmes à mieux comprendre leur corps.',
    keywords: ['pourquoi', 'existes'],
    disclaimer: false,
  },
  {
    id: 'S2_15',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S2_identity',
    question: 'Tu fais partie de l’application ?',
    answer: 'Oui 😊 Je suis intégrée à Nye Cyclea.',
    keywords: ['partie', 'app'],
    disclaimer: false,
  },
  {
    id: 'S2_16',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S2_identity',
    question: 'Tu es gratuite ?',
    answer: 'Oui, je suis incluse dans l’application.',
    keywords: ['gratuit', 'payant'],
    disclaimer: false,
  },
  {
    id: 'S2_17',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S2_identity',
    question: 'Tu es toujours disponible ?',
    answer: 'Oui, 24h/24.',
    keywords: ['disponible', 'quand'],
    disclaimer: false,
  },
  {
    id: 'S2_18',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S2_identity',
    question: 'Tu réponds hors ligne ?',
    answer: 'Oui 👍 Je fonctionne même sans Internet.',
    keywords: ['hors', 'ligne', 'internet'],
    disclaimer: false,
  },
  {
    id: 'S2_19',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S2_identity',
    question: 'Tu es une vraie personne ?',
    answer: 'Non. Je suis un assistant virtuel.',
    keywords: ['vrai', 'personne'],
    disclaimer: false,
  },
  {
    id: 'S2_20',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S2_identity',
    question: 'Tu es intelligente ?',
    answer: 'Je suis conçue pour répondre à des questions courantes.',
    keywords: ['intelligent'],
    disclaimer: false,
  },
  {
    id: 'S2_21',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S2_identity',
    question: 'Tu es locale ?',
    answer: 'Oui. Nye Cyclea est pensée pour les réalités locales.',
    keywords: ['local', 'afrique'],
    disclaimer: false,
  },
  {
    id: 'S2_22',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S2_identity',
    question: 'Tu parles quelle langue ?',
    answer: 'Je parle français et un langage simple et clair.',
    keywords: ['langue', 'francais'],
    disclaimer: false,
  },
  {
    id: 'S2_23',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S2_identity',
    question: 'Tu apprends ?',
    answer: 'Hors ligne, je fonctionne avec une base de connaissances fixe.',
    keywords: ['apprends', 'evolue'],
    disclaimer: false,
  },
  {
    id: 'S2_24',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S2_identity',
    question: 'Tu es fiable médicalement ?',
    answer: 'Je respecte des règles strictes de sécurité santé.',
    keywords: ['fiable', 'medical', 'sante'],
    disclaimer: true,
  },
  {
    id: 'S2_25',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S2_identity',
    question: 'Tu peux te tromper ?',
    answer: 'Oui. C’est pourquoi je ne remplace pas un professionnel de santé.',
    keywords: ['tromper', 'erreur'],
    disclaimer: false,
  },

  // 🔵 C. CE QUE LE CHATBOT PEUT FAIRE
  {
    id: 'S3_01',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S3_capabilities',
    question: 'Que fais-tu ?',
    answer: 'J’explique la santé féminine et le cycle menstruel.',
    keywords: ['fais', 'tu'],
    disclaimer: false,
  },
  {
    id: 'S3_02',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S3_capabilities',
    question: 'Tu peux m’aider ?',
    answer: 'Oui 😊 Avec des informations générales.',
    keywords: ['aider', 'aide'],
    disclaimer: false,
  },
  {
    id: 'S3_03',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S3_capabilities',
    question: 'Tu parles du cycle menstruel ?',
    answer: 'Oui 👍 C’est l’un de mes rôles principaux.',
    keywords: ['cycle', 'menstruel'],
    disclaimer: false,
  },
  {
    id: 'S3_04',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S3_capabilities',
    question: 'Tu aides à comprendre les règles ?',
    answer: 'Oui. J’explique leur fonctionnement.',
    keywords: ['regles', 'comprendre'],
    disclaimer: false,
  },
  {
    id: 'S3_05',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S3_capabilities',
    question: 'Tu donnes des conseils santé ?',
    answer: 'Je donne des informations générales, pas des conseils médicaux.',
    keywords: ['conseil', 'sante'],
    disclaimer: true,
  },
  {
    id: 'S3_06',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S3_capabilities',
    question: 'Tu expliques les phases du cycle ?',
    answer: 'Oui 😊',
    keywords: ['phases', 'cycle'],
    disclaimer: false,
  },
  {
    id: 'S3_07',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S3_capabilities',
    question: 'Tu aides à suivre le cycle ?',
    answer: 'Je peux expliquer comment mieux le comprendre.',
    keywords: ['suivre', 'cycle'],
    disclaimer: false,
  },
  {
    id: 'S3_08',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S3_capabilities',
    question: 'Tu parles d’hygiène menstruelle ?',
    answer: 'Oui 👍',
    keywords: ['hygiene', 'menstruelle'],
    disclaimer: false,
  },
  {
    id: 'S3_09',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S3_capabilities',
    question: 'Tu aides les jeunes filles ?',
    answer: 'Oui. Je fournis des informations éducatives adaptées.',
    keywords: ['jeune', 'fille', 'ado'],
    disclaimer: false,
  },
  {
    id: 'S3_10',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S3_capabilities',
    question: 'Tu peux rassurer ?',
    answer: 'Oui. Je donne des informations claires et neutres.',
    keywords: ['rassurer', 'peur'],
    disclaimer: false,
  },
  {
    id: 'S3_11',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S3_capabilities',
    question: 'Tu aides sans Internet ?',
    answer: 'Oui. Je fonctionne hors ligne.',
    keywords: ['sans', 'internet'],
    disclaimer: false,
  },
  {
    id: 'S3_12',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S3_capabilities',
    question: 'Tu peux répondre rapidement ?',
    answer: 'Oui 😊',
    keywords: ['rapide'],
    disclaimer: false,
  },
  {
    id: 'S3_13',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S3_capabilities',
    question: 'Tu expliques les symptômes courants ?',
    answer: 'Oui, de manière générale.',
    keywords: ['symptome', 'courant'],
    disclaimer: false,
  },
  {
    id: 'S3_14',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S3_capabilities',
    question: 'Tu peux expliquer le SPM ?',
    answer: 'Oui 👍',
    keywords: ['spm'],
    disclaimer: false,
  },
  {
    id: 'S3_15',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S3_capabilities',
    question: 'Tu parles des hormones ?',
    answer: 'Oui, à un niveau éducatif.',
    keywords: ['hormone'],
    disclaimer: false,
  },
  {
    id: 'S3_16',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S3_capabilities',
    question: 'Tu aides à mieux se connaître ?',
    answer: 'Oui. Comprendre son cycle aide beaucoup.',
    keywords: ['connaitre', 'soi'],
    disclaimer: false,
  },
  {
    id: 'S3_17',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S3_capabilities',
    question: 'Tu parles de bien-être féminin ?',
    answer: 'Oui 😊',
    keywords: ['bien', 'etre'],
    disclaimer: false,
  },
  {
    id: 'S3_18',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S3_capabilities',
    question: 'Tu aides à mieux vivre les règles ?',
    answer: 'Oui, par des informations générales.',
    keywords: ['vivre', 'regles'],
    disclaimer: false,
  },
  {
    id: 'S3_19',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S3_capabilities',
    question: 'Tu es là pour écouter ?',
    answer: 'Je suis là pour informer et orienter.',
    keywords: ['ecouter'],
    disclaimer: false,
  },
  {
    id: 'S3_20',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S3_capabilities',
    question: 'Tu peux expliquer les changements du corps ?',
    answer: 'Oui 👍',
    keywords: ['changement', 'corps'],
    disclaimer: false,
  },
  {
    id: 'S3_21',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S3_capabilities',
    question: 'Tu parles aux adolescentes ?',
    answer: 'Oui. Les informations sont éducatives.',
    keywords: ['ado', 'adolescente'],
    disclaimer: false,
  },
  {
    id: 'S3_22',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S3_capabilities',
    question: 'Tu parles aux femmes adultes ?',
    answer: 'Oui 😊',
    keywords: ['femme', 'adulte'],
    disclaimer: false,
  },
  {
    id: 'S3_23',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S3_capabilities',
    question: 'Tu es utile même hors ligne ?',
    answer: 'Oui. C’est un de mes avantages.',
    keywords: ['utile', 'hors', 'ligne'],
    disclaimer: false,
  },
  {
    id: 'S3_24',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S3_capabilities',
    question: 'Tu expliques ce qui est normal ?',
    answer: 'Oui, de façon générale.',
    keywords: ['normal'],
    disclaimer: false,
  },
  {
    id: 'S3_25',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S3_capabilities',
    question: 'Tu aides à comprendre son corps ?',
    answer: 'Oui 👍',
    keywords: ['comprendre', 'corps'],
    disclaimer: false,
  },

  // 🔴 D. LIMITES & SÉCURITÉ
  {
    id: 'S4_01',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S4_limits',
    question: 'Tu fais des diagnostics ?',
    answer: 'Non ❌',
    keywords: ['diagnostic'],
    disclaimer: true,
  },
  {
    id: 'S4_02',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S4_limits',
    question: 'Tu prescris des médicaments ?',
    answer: 'Non ❌',
    keywords: ['medicament', 'ordonnance'],
    disclaimer: true,
  },
  {
    id: 'S4_03',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S4_limits',
    question: 'Tu remplaces un médecin ?',
    answer: 'Non ❌',
    keywords: ['remplace', 'medecin'],
    disclaimer: true,
  },
  {
    id: 'S4_04',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S4_limits',
    question: 'Tu peux dire si je suis malade ?',
    answer: 'Non. Consulte un professionnel de santé.',
    keywords: ['malade', 'maladie'],
    disclaimer: true,
  },
  {
    id: 'S4_05',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S4_limits',
    question: 'Tu peux traiter une maladie ?',
    answer: 'Non ❌',
    keywords: ['traiter', 'soigner'],
    disclaimer: true,
  },
  {
    id: 'S4_06',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S4_limits',
    question: 'Tu peux dire quoi faire exactement ?',
    answer: 'Je donne seulement des informations générales.',
    keywords: ['quoi', 'faire'],
    disclaimer: false,
  },
  {
    id: 'S4_07',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S4_limits',
    question: 'Tu peux décider pour moi ?',
    answer: 'Non. Tu restes responsable de ta santé.',
    keywords: ['decider', 'responsable'],
    disclaimer: false,
  },
  {
    id: 'S4_08',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S4_limits',
    question: 'Tu peux analyser mes symptômes personnels ?',
    answer: 'Non ❌',
    keywords: ['analyser', 'symptome'],
    disclaimer: true,
  },
  {
    id: 'S4_09',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S4_limits',
    question: 'Tu peux faire un suivi médical ?',
    answer: 'Non ❌',
    keywords: ['suivi', 'medical'],
    disclaimer: true,
  },
  {
    id: 'S4_10',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S4_limits',
    question: 'Tu es sûre à 100 % ?',
    answer: 'Je fournis des informations éducatives, pas absolues.',
    keywords: ['sure', 'certaine'],
    disclaimer: true,
  },
  {
    id: 'S4_11',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S4_limits',
    question: 'Que faire en cas de douleur grave ?',
    answer: 'Consulte un professionnel de santé.',
    keywords: ['douleur', 'grave'],
    disclaimer: true,
  },
  {
    id: 'S4_12',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S4_limits',
    question: 'Que faire en cas d’urgence ?',
    answer: 'Contacte un service médical immédiatement.',
    keywords: ['urgence', 'urgent'],
    disclaimer: true,
  },
  {
    id: 'S4_13',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S4_limits',
    question: 'Tu peux parler de grossesse compliquée ?',
    answer: 'Non. Consulte un professionnel de santé.',
    keywords: ['grossesse', 'complique'],
    disclaimer: true,
  },
  {
    id: 'S4_14',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S4_limits',
    question: 'Tu peux parler de maladies graves ?',
    answer: 'De manière générale seulement.',
    keywords: ['maladie', 'grave'],
    disclaimer: true,
  },
  {
    id: 'S4_15',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S4_limits',
    question: 'Tu peux remplacer un centre de santé ?',
    answer: 'Non ❌',
    keywords: ['centre', 'sante'],
    disclaimer: true,
  },
  {
    id: 'S4_16',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S4_limits',
    question: 'Tu peux donner des traitements naturels ?',
    answer: 'Non. Je reste éducative.',
    keywords: ['traitement', 'naturel'],
    disclaimer: true,
  },
  {
    id: 'S4_17',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S4_limits',
    question: 'Tu es responsable de ma santé ?',
    answer: 'Non. Je suis un outil d’information.',
    keywords: ['responsable'],
    disclaimer: true,
  },
  {
    id: 'S4_18',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S4_limits',
    question: 'Tu peux garantir un résultat ?',
    answer: 'Non ❌',
    keywords: ['garantir', 'resultat'],
    disclaimer: true,
  },
  {
    id: 'S4_19',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S4_limits',
    question: 'Tu es un docteur virtuel ?',
    answer: 'Non ❌',
    keywords: ['docteur', 'virtuel'],
    disclaimer: true,
  },
  {
    id: 'S4_20',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S4_limits',
    question: 'Tu fais des analyses médicales ?',
    answer: 'Non ❌',
    keywords: ['analyse', 'medicale'],
    disclaimer: true,
  },
  {
    id: 'S4_21',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S4_limits',
    question: 'Tu peux me dire quoi prendre ?',
    answer: 'Non ❌',
    keywords: ['prendre', 'medicament'],
    disclaimer: true,
  },
  {
    id: 'S4_22',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S4_limits',
    question: 'Tu peux décider si c’est grave ?',
    answer: 'Non ❌',
    keywords: ['grave'],
    disclaimer: true,
  },
  {
    id: 'S4_23',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S4_limits',
    question: 'Tu peux me soigner ?',
    answer: 'Non ❌',
    keywords: ['soigner'],
    disclaimer: true,
  },
  {
    id: 'S4_24',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S4_limits',
    question: 'Tu es un hôpital ?',
    answer: 'Non ❌',
    keywords: ['hopital'],
    disclaimer: true,
  },
  {
    id: 'S4_25',
    category: 'greetings_identity_nye_cyclea',
    subCategory: 'S4_limits',
    question: 'À quoi s’arrête ton rôle ?',
    answer:
      'Mon rôle est éducatif. Pour tout problème sérieux, consulte un professionnel de santé.',
    keywords: ['role', 'limite'],
    disclaimer: true,
  },

  // 🩸 M. CYCLE MENSTRUEL (M_01 to M_40)
  {
    id: 'M_01',
    category: 'menstrual_cycle',
    subCategory: 'M_definitions',
    question: 'Qu’est-ce que le cycle menstruel ?',
    answer:
      'Le cycle menstruel correspond à l’ensemble des changements naturels que le corps féminin traverse chaque mois. Il commence le premier jour des règles et se termine la veille des règles suivantes.',
    keywords: ['cycle', 'menstruel', 'definition'],
    disclaimer: false,
  },
  {
    id: 'M_02',
    category: 'menstrual_cycle',
    subCategory: 'M_definitions',
    question: 'Pourquoi le cycle menstruel existe-t-il ?',
    answer:
      'Le cycle menstruel permet au corps de se préparer chaque mois à une éventuelle grossesse. Même sans grossesse, ce mécanisme continue naturellement.',
    keywords: ['pourquoi', 'existe'],
    disclaimer: false,
  },
  {
    id: 'M_03',
    category: 'menstrual_cycle',
    subCategory: 'M_definitions',
    question: 'À quel moment commence un cycle menstruel ?',
    answer:
      'Un cycle commence toujours le premier jour des règles, c’est-à-dire dès l’apparition du saignement.',
    keywords: ['commence', 'debut', 'cycle'],
    disclaimer: false,
  },
  {
    id: 'M_04',
    category: 'menstrual_cycle',
    subCategory: 'M_definitions',
    question: 'Pourquoi la durée du cycle varie-t-elle d’une femme à une autre ?',
    answer:
      'Chaque corps est unique. Les hormones, le stress, l’alimentation, l’âge et le mode de vie influencent la durée du cycle.',
    keywords: ['duree', 'varie', 'femme'],
    disclaimer: false,
  },
  {
    id: 'M_05',
    category: 'menstrual_cycle',
    subCategory: 'M_definitions',
    question: 'Quelle est la durée moyenne d’un cycle menstruel ?',
    answer:
      'La durée moyenne d’un cycle est souvent comprise entre 21 et 35 jours, mais des variations restent normales.',
    keywords: ['duree', 'moyenne'],
    disclaimer: false,
  },
  {
    id: 'M_06',
    category: 'menstrual_cycle',
    subCategory: 'M_definitions',
    question: 'Qu’est-ce que les règles exactement ?',
    answer:
      'Les règles correspondent à l’élimination de la muqueuse de l’utérus lorsque la grossesse n’a pas eu lieu.',
    keywords: ['regles', 'exactement'],
    disclaimer: false,
  },
  {
    id: 'M_07',
    category: 'menstrual_cycle',
    subCategory: 'M_definitions',
    question: 'Pourquoi les règles s’accompagnent-elles de saignements ?',
    answer:
      'Le saignement est dû à la perte de la muqueuse utérine, riche en sang, qui s’était préparée à accueillir une grossesse.',
    keywords: ['saignements', 'pourquoi'],
    disclaimer: false,
  },
  {
    id: 'M_08',
    category: 'menstrual_cycle',
    subCategory: 'M_definitions',
    question: 'Pourquoi certaines règles sont-elles plus abondantes que d’autres ?',
    answer:
      'L’abondance des règles peut varier selon les hormones, la santé générale, le stress ou certains changements corporels.',
    keywords: ['abondantes', 'regles'],
    disclaimer: false,
  },
  {
    id: 'M_09',
    category: 'menstrual_cycle',
    subCategory: 'M_definitions',
    question: 'Est-il normal que la couleur du sang menstruel change ?',
    answer:
      'Oui. Le sang peut être rouge vif, foncé ou brun selon le moment des règles et la vitesse d’écoulement.',
    keywords: ['couleur', 'sang', 'change'],
    disclaimer: false,
  },
  {
    id: 'M_10',
    category: 'menstrual_cycle',
    subCategory: 'M_phases',
    question: 'Qu’est-ce que la phase folliculaire ?',
    answer:
      'La phase folliculaire est la période qui commence après les règles. Le corps se prépare progressivement à l’ovulation.',
    keywords: ['phase', 'folliculaire'],
    disclaimer: false,
  },
  {
    id: 'M_11',
    category: 'menstrual_cycle',
    subCategory: 'M_phases',
    question: 'Que se passe-t-il pendant l’ovulation ?',
    answer:
      'Pendant l’ovulation, un ovule est libéré par l’ovaire. C’est la période où une grossesse peut survenir.',
    keywords: ['ovulation', 'passe'],
    disclaimer: false,
  },
  {
    id: 'M_12',
    category: 'menstrual_cycle',
    subCategory: 'M_phases',
    question: 'Pourquoi l’ovulation ne se produit pas toujours au même jour ?',
    answer:
      'Les hormones, le stress et la santé globale peuvent influencer le moment exact de l’ovulation.',
    keywords: ['ovulation', 'jour'],
    disclaimer: false,
  },
  {
    id: 'M_13',
    category: 'menstrual_cycle',
    subCategory: 'M_phases',
    question: 'Qu’est-ce que la phase lutéale ?',
    answer:
      'La phase lutéale correspond à la période après l’ovulation, durant laquelle le corps attend une éventuelle grossesse.',
    keywords: ['phase', 'luteale'],
    disclaimer: false,
  },
  {
    id: 'M_14',
    category: 'menstrual_cycle',
    subCategory: 'M_symptoms',
    question: 'Pourquoi certaines femmes ressentent-elles des douleurs pendant le cycle ?',
    answer:
      'Les douleurs peuvent être liées aux contractions de l’utérus, aux hormones ou à la sensibilité individuelle.',
    keywords: ['douleurs', 'cycle'],
    disclaimer: false,
  },
  {
    id: 'M_15',
    category: 'menstrual_cycle',
    subCategory: 'M_symptoms',
    question: 'Pourquoi les seins peuvent-ils être sensibles avant les règles ?',
    answer:
      'Les variations hormonales peuvent provoquer une rétention d’eau et une sensibilité des seins avant les règles.',
    keywords: ['seins', 'sensibles'],
    disclaimer: false,
  },
  {
    id: 'M_16',
    category: 'menstrual_cycle',
    subCategory: 'M_symptoms',
    question: 'Pourquoi l’humeur peut-elle changer au cours du cycle ? ',
    answer:
      'Les hormones influencent le cerveau et les émotions, ce qui peut expliquer les variations d’humeur.',
    keywords: ['humeur', 'changer'],
    disclaimer: false,
  },
  {
    id: 'M_17',
    category: 'menstrual_cycle',
    subCategory: 'M_symptoms',
    question: 'Qu’est-ce que le syndrome prémenstruel (SPM) ?',
    answer:
      'Le SPM regroupe des symptômes physiques et émotionnels pouvant apparaître avant les règles.',
    keywords: ['spm', 'syndrome'],
    disclaimer: false,
  },
  {
    id: 'M_18',
    category: 'menstrual_cycle',
    subCategory: 'M_irregularities',
    question: 'Pourquoi certaines femmes ont-elles des cycles irréguliers ?',
    answer:
      'Les cycles irréguliers peuvent être liés au stress, à l’alimentation, aux changements hormonaux ou à certaines conditions de santé.',
    keywords: ['cycles', 'irreguliers'],
    disclaimer: false,
  },
  {
    id: 'M_19',
    category: 'menstrual_cycle',
    subCategory: 'M_lifestyle',
    question: 'En quoi le stress influence-t-il le cycle menstruel ?',
    answer: 'Le stress peut perturber les hormones, ce qui peut retarder ou avancer les règles.',
    keywords: ['stress', 'influence'],
    disclaimer: false,
  },
  {
    id: 'M_20',
    category: 'menstrual_cycle',
    subCategory: 'M_lifestyle',
    question: 'Pourquoi est-il utile de suivre son cycle menstruel ?',
    answer:
      'Suivre son cycle permet de mieux comprendre son corps, d’anticiper certains symptômes et de se sentir plus en confiance.',
    keywords: ['suivre', 'cycle', 'utile'],
    disclaimer: false,
  },
  {
    id: 'M_21',
    category: 'menstrual_cycle',
    subCategory: 'M_lifestyle',
    question: 'Comment le sommeil influence-t-il le cycle menstruel ?',
    answer:
      'Un sommeil insuffisant peut perturber les hormones et influencer la régularité du cycle.',
    keywords: ['sommeil', 'influence'],
    disclaimer: false,
  },
  {
    id: 'M_22',
    category: 'menstrual_cycle',
    subCategory: 'M_lifestyle',
    question: 'Pourquoi l’alimentation joue-t-elle un rôle dans le cycle ?',
    answer: 'Une alimentation équilibrée aide le corps à mieux gérer les variations hormonales.',
    keywords: ['alimentation', 'role'],
    disclaimer: false,
  },
  {
    id: 'M_23',
    category: 'menstrual_cycle',
    subCategory: 'M_lifestyle',
    question: 'Le cycle menstruel change-t-il avec l’âge ?',
    answer:
      'Oui. Le cycle évolue naturellement à l’adolescence, après les grossesses et à l’approche de la ménopause.',
    keywords: ['change', 'age'],
    disclaimer: false,
  },
  {
    id: 'M_24',
    category: 'menstrual_cycle',
    subCategory: 'M_irregularities',
    question: 'Pourquoi certaines femmes n’ont-elles pas de règles certains mois ?',
    answer:
      'L’absence de règles peut être liée au stress, à un changement important ou à une grossesse.',
    keywords: ['absence', 'regles'],
    disclaimer: false,
  },
  {
    id: 'M_25',
    category: 'menstrual_cycle',
    subCategory: 'M_lifestyle',
    question: 'Qu’est-ce qu’un cycle naturel ?',
    answer:
      'Un cycle naturel correspond à un cycle sans contraception hormonale, où le corps fonctionne selon ses hormones naturelles.',
    keywords: ['cycle', 'naturel'],
    disclaimer: false,
  },
  {
    id: 'M_26',
    category: 'menstrual_cycle',
    subCategory: 'M_lifestyle',
    question: 'En quoi la contraception peut-elle modifier le cycle ?',
    answer:
      'Certaines contraceptions modifient ou bloquent l’ovulation, ce qui change le fonctionnement du cycle.',
    keywords: ['contraception', 'modifier'],
    disclaimer: false,
  },
  {
    id: 'M_27',
    category: 'menstrual_cycle',
    subCategory: 'M_symptoms',
    question: 'Pourquoi certaines femmes ont-elles des cycles douloureux ?',
    answer:
      'La sensibilité à la douleur varie selon les femmes et peut être influencée par les hormones et l’utérus.',
    keywords: ['cycles', 'douloureux'],
    disclaimer: false,
  },
  {
    id: 'M_28',
    category: 'menstrual_cycle',
    subCategory: 'M_lifestyle',
    question: 'Est-il normal que les cycles changent après un accouchement ?',
    answer:
      'Oui. Le corps a besoin de temps pour retrouver un équilibre hormonal après une grossesse.',
    keywords: ['cycles', 'accouchement'],
    disclaimer: false,
  },
  {
    id: 'M_29',
    category: 'menstrual_cycle',
    subCategory: 'M_lifestyle',
    question:
      'Pourquoi certaines femmes ressentent-elles plus d’énergie à certains moments du cycle ?',
    answer:
      'Les variations hormonales peuvent influencer l’énergie, la motivation et la concentration.',
    keywords: ['energie', 'moments'],
    disclaimer: false,
  },
  {
    id: 'M_30',
    category: 'menstrual_cycle',
    subCategory: 'M_lifestyle',
    question: 'En quoi Nye Cyclea aide-t-elle à mieux vivre son cycle ?',
    answer:
      'Nye Cyclea permet de suivre son cycle même hors ligne et d’obtenir des explications adaptées aux réalités locales.',
    keywords: ['nye', 'cyclea', 'aide'],
    disclaimer: false,
  },
  {
    id: 'M_31',
    category: 'menstrual_cycle',
    subCategory: 'M_lifestyle',
    question: 'Pourquoi est-il important de connaître son propre cycle ?',
    answer: 'Connaître son cycle aide à mieux comprendre ses réactions physiques et émotionnelles.',
    keywords: ['connaitre', 'cycle'],
    disclaimer: false,
  },
  {
    id: 'M_32',
    category: 'menstrual_cycle',
    subCategory: 'M_lifestyle',
    question: 'Les cycles courts et longs sont-ils anormaux ?',
    answer: 'Un cycle peut être plus court ou plus long tout en restant normal s’il est régulier.',
    keywords: ['courts', 'longs', 'anormaux'],
    disclaimer: false,
  },
  {
    id: 'M_33',
    category: 'menstrual_cycle',
    subCategory: 'M_symptoms',
    question: 'Pourquoi les règles peuvent-elles être douloureuses certains mois seulement ?',
    answer: 'Les hormones, le stress ou la fatigue peuvent varier d’un cycle à l’autre.',
    keywords: ['douloureuses', 'mois'],
    disclaimer: false,
  },
  {
    id: 'M_34',
    category: 'menstrual_cycle',
    subCategory: 'M_lifestyle',
    question: 'Le cycle menstruel est-il le même toute la vie ?',
    answer: 'Non. Il évolue naturellement avec les étapes de la vie.',
    keywords: ['meme', 'vie'],
    disclaimer: false,
  },
  {
    id: 'M_35',
    category: 'menstrual_cycle',
    subCategory: 'M_lifestyle',
    question: 'Pourquoi le corps a-t-il besoin de repos pendant les règles ?',
    answer:
      'Pendant les règles, le corps travaille davantage, ce qui peut nécessiter plus de repos.',
    keywords: ['repos', 'regles'],
    disclaimer: false,
  },
  {
    id: 'M_36',
    category: 'menstrual_cycle',
    subCategory: 'M_lifestyle',
    question: 'Peut-on mieux organiser ses activités en fonction du cycle ?',
    answer: 'Comprendre son cycle peut aider à adapter ses activités selon l’énergie ressentie.',
    keywords: ['organiser', 'activites'],
    disclaimer: false,
  },
  {
    id: 'M_37',
    category: 'menstrual_cycle',
    subCategory: 'M_symptoms',
    question: 'Pourquoi certaines femmes ont-elles des saignements légers ?',
    answer:
      'Les saignements légers peuvent être liés à un cycle particulier ou à des variations hormonales.',
    keywords: ['saignements', 'legers'],
    disclaimer: false,
  },
  {
    id: 'M_38',
    category: 'menstrual_cycle',
    subCategory: 'M_lifestyle',
    question: 'Le cycle menstruel influence-t-il la concentration ?',
    answer: 'Oui. Les hormones peuvent influencer la mémoire et la concentration.',
    keywords: ['concentration', 'influence'],
    disclaimer: false,
  },
  {
    id: 'M_39',
    category: 'menstrual_cycle',
    subCategory: 'M_lifestyle',
    question: 'Pourquoi le cycle menstruel est-il différent chaque mois ?',
    answer: 'Même si le cycle suit une logique, de petits changements restent normaux.',
    keywords: ['different', 'mois'],
    disclaimer: false,
  },
  {
    id: 'M_40',
    category: 'menstrual_cycle',
    subCategory: 'M_limitations',
    question: 'Quand faut-il consulter un professionnel de santé ?',
    answer:
      'Il est conseillé de consulter en cas de douleurs intenses, de saignements inhabituels ou de changements soudains.',
    keywords: ['consulter', 'professionnel'],
    disclaimer: true,
  },

  // 🌸 SY. SYMPTÔMES & BIEN-ÊTRE (SY_01 to SY_40)
  {
    id: 'SY_01',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_pain',
    question: 'Pourquoi le bas-ventre peut-il être douloureux pendant les règles ?',
    answer:
      'Pendant les règles, l’utérus se contracte pour évacuer la muqueuse. Ces contractions peuvent provoquer des douleurs chez certaines femmes.',
    keywords: ['bas-ventre', 'douloureux', 'regles'],
    disclaimer: false,
  },
  {
    id: 'SY_02',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_pain',
    question: 'Pourquoi certaines douleurs ressemblent-elles à des crampes ?',
    answer:
      'Les crampes sont liées aux contractions musculaires de l’utérus, similaires à d’autres muscles du corps lorsqu’ils travaillent.',
    keywords: ['crampes', 'douleurs'],
    disclaimer: false,
  },
  {
    id: 'SY_03',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_pain',
    question: 'Pourquoi la douleur est-elle plus forte certains mois ?',
    answer:
      'Le niveau hormonal, le stress, la fatigue ou l’alimentation peuvent varier d’un cycle à l’autre et influencer l’intensité des douleurs.',
    keywords: ['douleur', 'forte', 'mois'],
    disclaimer: false,
  },
  {
    id: 'SY_04',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_pain',
    question: 'Pourquoi peut-on avoir mal au dos pendant les règles ?',
    answer:
      'Les nerfs de l’utérus sont proches de ceux du bas du dos, ce qui peut provoquer des douleurs dorsales.',
    keywords: ['mal', 'dos', 'regles'],
    disclaimer: false,
  },
  {
    id: 'SY_05',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_physical',
    question: 'Pourquoi certaines femmes ont-elles des maux de tête pendant le cycle ?',
    answer:
      'Les variations hormonales peuvent influencer la circulation sanguine et provoquer des maux de tête.',
    keywords: ['maux', 'tete', 'migraine'],
    disclaimer: false,
  },
  {
    id: 'SY_06',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_physical',
    question: 'Pourquoi se sent-on plus fatiguée pendant les règles ? ',
    answer:
      'La perte de sang et les changements hormonaux peuvent diminuer temporairement l’énergie du corps.',
    keywords: ['fatigue', 'fatiguee', 'energie'],
    disclaimer: false,
  },
  {
    id: 'SY_07',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_physical',
    question: 'Pourquoi peut-on avoir des vertiges pendant les règles ?',
    answer:
      'Les vertiges peuvent être liés à la fatigue, à une baisse de tension ou à une perte de sang plus importante.',
    keywords: ['vertiges', 'tournis'],
    disclaimer: true,
  },
  {
    id: 'SY_08',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_cravings',
    question: 'Pourquoi l’appétit change-t-il au cours du cycle ?',
    answer:
      'Les hormones influencent la sensation de faim et les envies alimentaires, surtout avant les règles.',
    keywords: ['appetit', 'faim', 'manger'],
    disclaimer: false,
  },
  {
    id: 'SY_09',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_cravings',
    question: 'Pourquoi certaines femmes ont-elles envie de sucre avant les règles ?',
    answer:
      'Le corps cherche parfois à compenser la fatigue et les variations hormonales par des aliments énergétiques.',
    keywords: ['sucre', 'envie', 'manger'],
    disclaimer: false,
  },
  {
    id: 'SY_10',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_physical',
    question: 'Pourquoi le ventre peut-il être gonflé avant ou pendant les règles ?',
    answer:
      'La rétention d’eau et les changements hormonaux peuvent provoquer une sensation de gonflement.',
    keywords: ['ventre', 'gonfle', 'ballonnement'],
    disclaimer: false,
  },
  {
    id: 'SY_11',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_physical',
    question: 'Pourquoi peut-on avoir des nausées pendant les règles ?',
    answer:
      'Les contractions de l’utérus et certaines hormones peuvent influencer le système digestif.',
    keywords: ['nausees', 'vomir', 'mal'],
    disclaimer: false,
  },
  {
    id: 'SY_12',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_physical',
    question: 'Pourquoi le transit intestinal change-t-il pendant le cycle ?',
    answer:
      'Les hormones du cycle menstruel influencent aussi les intestins, ce qui peut provoquer constipation ou diarrhée.',
    keywords: ['transit', 'digestion', 'constipation'],
    disclaimer: false,
  },
  {
    id: 'SY_13',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_emotional',
    question: 'Pourquoi certaines femmes se sentent plus sensibles émotionnellement ?',
    answer:
      'Les hormones influencent les émotions, ce qui peut augmenter la sensibilité ou l’irritabilité.',
    keywords: ['sensible', 'emotions', 'pleurer'],
    disclaimer: false,
  },
  {
    id: 'SY_14',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_emotional',
    question: 'Pourquoi l’anxiété peut-elle augmenter avant les règles ?',
    answer: 'Les variations hormonales peuvent influencer le stress et la gestion des émotions.',
    keywords: ['anxiete', 'stress', 'peur'],
    disclaimer: false,
  },
  {
    id: 'SY_15',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_emotional',
    question: 'Pourquoi peut-on se sentir triste sans raison apparente ?',
    answer: 'Les fluctuations hormonales peuvent agir sur les neurotransmetteurs liés à l’humeur.',
    keywords: ['triste', 'tristesse', 'deprime'],
    disclaimer: false,
  },
  {
    id: 'SY_16',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_mental',
    question: 'Pourquoi certaines femmes se sentent plus fatiguées mentalement ?',
    answer:
      'Le cycle peut influencer la concentration et la clarté mentale, surtout à certaines phases.',
    keywords: ['fatigue', 'mentale', 'tete'],
    disclaimer: false,
  },
  {
    id: 'SY_17',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_physical',
    question: 'Pourquoi la peau peut-elle changer au cours du cycle ?',
    answer:
      'Les hormones influencent la production de sébum, ce qui peut provoquer boutons ou peau plus grasse.',
    keywords: ['peau', 'boutons', 'acne'],
    disclaimer: false,
  },
  {
    id: 'SY_18',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_physical',
    question: 'Pourquoi des boutons apparaissent-ils avant les règles ?',
    answer: 'L’augmentation de certaines hormones peut stimuler les glandes sébacées.',
    keywords: ['boutons', 'visage'],
    disclaimer: false,
  },
  {
    id: 'SY_19',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_physical',
    question: 'Pourquoi les seins peuvent-ils être lourds ou douloureux ?',
    answer: 'Les variations hormonales provoquent une rétention d’eau et une sensibilité mammaire.',
    keywords: ['seins', 'poitrine', 'mal'],
    disclaimer: false,
  },
  {
    id: 'SY_20',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_physical',
    question: 'Pourquoi certaines femmes ressentent-elles plus de chaleur ?',
    answer: 'Les hormones peuvent influencer la température corporelle.',
    keywords: ['chaleur', 'chaud', 'temperature'],
    disclaimer: false,
  },
  {
    id: 'SY_21',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_sleep',
    question: 'Pourquoi le sommeil peut-il être perturbé ?',
    answer: 'Les changements hormonaux peuvent affecter la qualité et la durée du sommeil.',
    keywords: ['sommeil', 'dormir', 'insomnie'],
    disclaimer: false,
  },
  {
    id: 'SY_22',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_sleep',
    question: 'Pourquoi les rêves peuvent-ils être plus intenses ?',
    answer: 'Les phases du cycle peuvent influencer l’activité cérébrale pendant le sommeil.',
    keywords: ['reves', 'cauchemars'],
    disclaimer: false,
  },
  {
    id: 'SY_23',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_energy',
    question: 'Pourquoi certaines femmes ont-elles moins d’énergie à certains moments ?',
    answer: 'Les niveaux hormonaux influencent l’énergie physique et mentale.',
    keywords: ['energie', 'fatigue'],
    disclaimer: false,
  },
  {
    id: 'SY_24',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_emotional',
    question: 'Pourquoi l’envie de rester seule peut-elle augmenter ?',
    answer: 'La sensibilité émotionnelle peut donner besoin de calme et de repos.',
    keywords: ['seule', 'solitude', 'calme'],
    disclaimer: false,
  },
  {
    id: 'SY_25',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_energy',
    question: 'Pourquoi le corps demande-t-il plus de repos pendant les règles ?',
    answer: 'Le corps mobilise plus d’énergie pour gérer les changements internes.',
    keywords: ['repos', 'dormir'],
    disclaimer: false,
  },
  {
    id: 'SY_26',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_physical',
    question: 'Pourquoi certaines femmes ressentent-elles des douleurs dans les jambes ?',
    answer: 'Les hormones peuvent influencer la circulation et les tensions musculaires.',
    keywords: ['jambes', 'douleurs', 'mal'],
    disclaimer: false,
  },
  {
    id: 'SY_27',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_mental',
    question: 'Pourquoi la motivation peut-elle diminuer ?',
    answer: 'Les hormones influencent la dopamine, liée à la motivation.',
    keywords: ['motivation', 'envie'],
    disclaimer: false,
  },
  {
    id: 'SY_28',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_mental',
    question: 'Pourquoi certaines femmes se sentent-elles plus créatives à certains moments ?',
    answer: 'Certaines phases du cycle sont associées à une meilleure énergie mentale.',
    keywords: ['creative', 'idee'],
    disclaimer: false,
  },
  {
    id: 'SY_29',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_mental',
    question: 'Pourquoi le stress est-il plus difficile à gérer pendant certaines périodes ?',
    answer: 'Les hormones peuvent réduire la tolérance au stress.',
    keywords: ['stress', 'gerer'],
    disclaimer: false,
  },
  {
    id: 'SY_30',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_emotional',
    question: 'Pourquoi certaines femmes ressentent-elles un besoin de réconfort ?',
    answer: 'Les changements émotionnels peuvent augmenter le besoin de sécurité affective.',
    keywords: ['reconfort', 'calin'],
    disclaimer: false,
  },
  {
    id: 'SY_31',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_sensations',
    question: 'Pourquoi les sensations corporelles sont-elles plus fortes ?',
    answer: 'La sensibilité nerveuse peut varier selon les phases du cycle.',
    keywords: ['sensations', 'corps'],
    disclaimer: false,
  },
  {
    id: 'SY_32',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_sensations',
    question: 'Pourquoi certaines femmes ressentent-elles un malaise général ?',
    answer: 'La combinaison de fatigue, hormones et douleurs peut provoquer ce ressenti.',
    keywords: ['malaise', 'pas', 'bien'],
    disclaimer: false,
  },
  {
    id: 'SY_33',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_pain',
    question: 'Pourquoi certaines douleurs disparaissent après les règles ?',
    answer: 'Une fois les hormones stabilisées, le corps retrouve son équilibre.',
    keywords: ['disparait', 'fin'],
    disclaimer: false,
  },
  {
    id: 'SY_34',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_relief',
    question: 'Pourquoi l’activité physique peut-elle parfois soulager ?',
    answer: 'Le mouvement peut améliorer la circulation et réduire les tensions.',
    keywords: ['sport', 'activite', 'soulager'],
    disclaimer: false,
  },
  {
    id: 'SY_35',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_relief',
    question: 'Pourquoi certaines femmes se sentent mieux après s’être reposées ?',
    answer: 'Le repos aide le corps à récupérer de l’énergie.',
    keywords: ['mieux', 'repos'],
    disclaimer: false,
  },
  {
    id: 'SY_36',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_relief',
    question: 'Pourquoi boire de l’eau est important pendant les règles ?',
    answer: 'Une bonne hydratation aide à limiter la fatigue et la rétention d’eau.',
    keywords: ['boire', 'eau', 'hydratation'],
    disclaimer: false,
  },
  {
    id: 'SY_37',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_general',
    question: 'Pourquoi écouter son corps est essentiel pendant le cycle ?',
    answer: 'Le corps envoie des signaux qui aident à adapter son rythme.',
    keywords: ['ecouter', 'corps'],
    disclaimer: false,
  },
  {
    id: 'SY_38',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_general',
    question: 'Pourquoi comparer son cycle à celui des autres peut être trompeur ?',
    answer: 'Chaque corps fonctionne différemment et a son propre rythme.',
    keywords: ['comparer', 'autres'],
    disclaimer: false,
  },
  {
    id: 'SY_39',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_general',
    question: 'Pourquoi certaines femmes apprennent à mieux se connaître grâce à leur cycle ?',
    answer: 'Observer le cycle permet de comprendre ses réactions physiques et émotionnelles.',
    keywords: ['connaitre', 'apprendre'],
    disclaimer: false,
  },
  {
    id: 'SY_40',
    category: 'symptoms_wellbeing',
    subCategory: 'SY_general',
    question: 'En quoi Nye Cyclea aide au bien-être quotidien ?',
    answer:
      'Nye Cyclea accompagne les utilisatrices en expliquant les sensations et en aidant à mieux vivre chaque phase du cycle, même hors ligne.',
    keywords: ['nye', 'cyclea', 'aide'],
    disclaimer: false,
  },

  // 🌿 HA. HABITUDES & ORGANISATION (HA_01 to HA_40)
  {
    id: 'HA_01',
    category: 'habits_organization',
    subCategory: 'HA_rest',
    question: 'Comment mieux se reposer pendant les règles ?',
    answer:
      'Pendant les règles, le corps travaille davantage. Réduire le rythme, dormir un peu plus et éviter les efforts excessifs peut aider à mieux récupérer.',
    keywords: ['reposer', 'repos', 'dormir'],
    disclaimer: false,
  },
  {
    id: 'HA_02',
    category: 'habits_organization',
    subCategory: 'HA_daily',
    question: 'Comment adapter ses activités quotidiennes pendant les règles ?',
    answer:
      'Il peut être utile de privilégier les tâches légères et de s’accorder des pauses lorsque le corps en ressent le besoin.',
    keywords: ['activites', 'quotidiennes'],
    disclaimer: false,
  },
  {
    id: 'HA_03',
    category: 'habits_organization',
    subCategory: 'HA_health',
    question: 'Comment mieux gérer la fatigue liée au cycle menstruel ?',
    answer:
      'La fatigue peut être mieux gérée en respectant les temps de repos, en mangeant régulièrement et en buvant suffisamment d’eau.',
    keywords: ['fatigue', 'gerer'],
    disclaimer: false,
  },
  {
    id: 'HA_04',
    category: 'habits_organization',
    subCategory: 'HA_planning',
    question: 'Comment organiser son emploi du temps en fonction de son cycle ?',
    answer:
      'Observer les périodes où l’énergie est plus élevée permet de planifier les tâches importantes à ces moments-là.',
    keywords: ['organiser', 'emploi', 'temps'],
    disclaimer: false,
  },
  {
    id: 'HA_05',
    category: 'habits_organization',
    subCategory: 'HA_selfcare',
    question: 'Comment prendre soin de son corps avant les règles ?',
    answer:
      'Avant les règles, ralentir le rythme, bien dormir et réduire le stress peut aider à mieux vivre cette période.',
    keywords: ['soin', 'corps', 'avant'],
    disclaimer: false,
  },
  {
    id: 'HA_06',
    category: 'habits_organization',
    subCategory: 'HA_daily',
    question: 'Comment mieux vivre les règles à l’école ou au travail ?',
    answer:
      'Prévoir des protections adaptées, porter des vêtements confortables et s’accorder des moments de repos aide à se sentir plus à l’aise.',
    keywords: ['ecole', 'travail', 'boulot'],
    disclaimer: false,
  },
  {
    id: 'HA_07',
    category: 'habits_organization',
    subCategory: 'HA_pain',
    question: 'Comment gérer les douleurs menstruelles au quotidien ?',
    answer:
      'Le repos, la chaleur sur le ventre et une activité douce peuvent aider à soulager les inconforts.',
    keywords: ['gerer', 'douleurs'],
    disclaimer: false,
  },
  {
    id: 'HA_08',
    category: 'habits_organization',
    subCategory: 'HA_hygiene',
    question: 'Comment l’hygiène intime doit-elle être adaptée pendant les règles ?',
    answer:
      'Une hygiène douce, sans produits agressifs, permet de respecter l’équilibre naturel du corps.',
    keywords: ['hygiene', 'toilette'],
    disclaimer: false,
  },
  {
    id: 'HA_09',
    category: 'habits_organization',
    subCategory: 'HA_hygiene',
    question: 'Comment choisir une protection menstruelle adaptée ?',
    answer:
      'Le choix dépend du confort, des habitudes et de ce qui est disponible localement. L’important est de se sentir à l’aise et en sécurité.',
    keywords: ['protection', 'serviette', 'tampon'],
    disclaimer: false,
  },
  {
    id: 'HA_10',
    category: 'habits_organization',
    subCategory: 'HA_hygiene',
    question: 'Comment changer ses protections menstruelles correctement ?',
    answer:
      'Changer régulièrement ses protections aide à éviter l’inconfort et à maintenir une bonne hygiène.',
    keywords: ['changer', 'protection'],
    disclaimer: false,
  },
  {
    id: 'HA_11',
    category: 'habits_organization',
    subCategory: 'HA_comfort',
    question: 'Comment éviter l’inconfort pendant les règles ?',
    answer:
      'Porter des vêtements amples, rester hydratée et écouter son corps peut réduire l’inconfort.',
    keywords: ['inconfort', 'gene'],
    disclaimer: false,
  },
  {
    id: 'HA_12',
    category: 'habits_organization',
    subCategory: 'HA_rest',
    question: 'Comment mieux dormir pendant les règles ?',
    answer:
      'Créer un environnement calme, se coucher plus tôt et adopter une position confortable peut améliorer le sommeil.',
    keywords: ['dormir', 'sommeil'],
    disclaimer: false,
  },
  {
    id: 'HA_13',
    category: 'habits_organization',
    subCategory: 'HA_health',
    question: 'Comment gérer les ballonnements pendant le cycle ?',
    answer:
      'Boire de l’eau, manger lentement et éviter les repas trop lourds peut aider à limiter cette sensation.',
    keywords: ['ballonnements', 'ventre'],
    disclaimer: false,
  },
  {
    id: 'HA_14',
    category: 'habits_organization',
    subCategory: 'HA_health',
    question: 'Comment adapter son alimentation pendant le cycle menstruel ?',
    answer:
      'Privilégier des repas équilibrés aide le corps à mieux gérer les variations hormonales.',
    keywords: ['alimentation', 'manger'],
    disclaimer: false,
  },
  {
    id: 'HA_15',
    category: 'habits_organization',
    subCategory: 'HA_stress',
    question: 'Comment réduire la sensation de stress avant les règles ?',
    answer:
      'Prendre du temps pour soi, respirer profondément et réduire les sources de pression peut aider à apaiser le stress.',
    keywords: ['stress', 'reduire'],
    disclaimer: false,
  },
  {
    id: 'HA_16',
    category: 'habits_organization',
    subCategory: 'HA_selfcare',
    question: 'Comment écouter les signaux de son corps ?',
    answer:
      'Être attentive à la fatigue, aux douleurs ou aux émotions permet d’adapter son rythme quotidien.',
    keywords: ['signaux', 'ecouter'],
    disclaimer: false,
  },
  {
    id: 'HA_17',
    category: 'habits_organization',
    subCategory: 'HA_emotional',
    question: 'Comment gérer les changements d’humeur au quotidien ?',
    answer:
      'Reconnaître que ces changements sont liés au cycle aide à les vivre avec plus de compréhension et de patience.',
    keywords: ['humeur', 'gestion'],
    disclaimer: false,
  },
  {
    id: 'HA_18',
    category: 'habits_organization',
    subCategory: 'HA_activity',
    question: 'Comment rester active tout en respectant son corps ?',
    answer:
      'Des activités douces comme la marche ou les étirements peuvent être adaptées à certaines phases du cycle.',
    keywords: ['active', 'sport', 'bouger'],
    disclaimer: false,
  },
  {
    id: 'HA_19',
    category: 'habits_organization',
    subCategory: 'HA_energy',
    question: 'Comment mieux gérer les journées avec peu d’énergie ?',
    answer: 'Réduire les obligations non essentielles et se concentrer sur l’essentiel peut aider.',
    keywords: ['energie', 'faible'],
    disclaimer: false,
  },
  {
    id: 'HA_20',
    category: 'habits_organization',
    subCategory: 'HA_emotional',
    question: 'Comment se préparer mentalement à l’arrivée des règles ?',
    answer: 'Connaître son cycle permet d’anticiper cette période et de mieux l’accepter.',
    keywords: ['preparer', 'mentalement'],
    disclaimer: false,
  },
  {
    id: 'HA_21',
    category: 'habits_organization',
    subCategory: 'HA_context',
    question: 'Comment mieux vivre les règles dans un contexte de contraintes locales ?',
    answer:
      'S’adapter aux ressources disponibles et privilégier le confort et l’hygiène est essentiel.',
    keywords: ['contexte', 'local'],
    disclaimer: false,
  },
  {
    id: 'HA_22',
    category: 'habits_organization',
    subCategory: 'HA_social',
    question: 'Comment parler de ses règles sans gêne ?',
    answer:
      'Comprendre que les règles sont naturelles peut aider à en parler avec plus de sérénité.',
    keywords: ['parler', 'discuter', 'gene'],
    disclaimer: false,
  },
  {
    id: 'HA_23',
    category: 'habits_organization',
    subCategory: 'HA_daily',
    question: 'Comment mieux gérer les règles lors des déplacements ?',
    answer: 'Prévoir des protections à l’avance et s’organiser permet de réduire le stress.',
    keywords: ['deplacement', 'voyage'],
    disclaimer: false,
  },
  {
    id: 'HA_24',
    category: 'habits_organization',
    subCategory: 'HA_hygiene',
    question: 'Comment maintenir une bonne hygiène quand l’accès à l’eau est limité ?',
    answer:
      'Utiliser de l’eau propre quand c’est possible et changer régulièrement les protections aide à maintenir l’hygiène.',
    keywords: ['eau', 'limitee', 'hygiene'],
    disclaimer: false,
  },
  {
    id: 'HA_25',
    category: 'habits_organization',
    subCategory: 'HA_emotional',
    question: 'Comment prendre soin de soi émotionnellement pendant le cycle ?',
    answer: 'S’accorder de la bienveillance et éviter l’auto-culpabilisation est important.',
    keywords: ['emotionnellement', 'soin'],
    disclaimer: false,
  },
  {
    id: 'HA_26',
    category: 'habits_organization',
    subCategory: 'HA_selfcare',
    question: 'Comment reconnaître ses limites pendant le cycle ?',
    answer:
      'La fatigue ou l’irritabilité peuvent être des signes indiquant qu’il est temps de ralentir.',
    keywords: ['limites', 'reconparaitre'],
    disclaimer: false,
  },
  {
    id: 'HA_27',
    category: 'habits_organization',
    subCategory: 'HA_social',
    question: 'Comment éviter de se comparer aux autres femmes ?',
    answer: 'Chaque corps fonctionne différemment et a son propre rythme.',
    keywords: ['comparer', 'autres'],
    disclaimer: false,
  },
  {
    id: 'HA_28',
    category: 'habits_organization',
    subCategory: 'HA_pain',
    question: 'Comment mieux gérer les douleurs légères sans se forcer ?',
    answer: 'Le repos et l’écoute du corps permettent souvent de réduire ces douleurs.',
    keywords: ['douleurs', 'legeres'],
    disclaimer: false,
  },
  {
    id: 'HA_29',
    category: 'habits_organization',
    subCategory: 'HA_health',
    question: 'Comment améliorer son bien-être général pendant le cycle ?',
    answer:
      'Adopter des habitudes régulières de repos, d’alimentation et de gestion du stress aide sur le long terme.',
    keywords: ['bien-etre', 'general'],
    disclaimer: false,
  },
  {
    id: 'HA_30',
    category: 'habits_organization',
    subCategory: 'HA_confidence',
    question: 'Comment se sentir plus en confiance pendant les règles ?',
    answer: 'Se préparer à l’avance et connaître son corps permet de réduire l’anxiété.',
    keywords: ['confiance', 'assurance'],
    disclaimer: false,
  },
  {
    id: 'HA_31',
    category: 'habits_organization',
    subCategory: 'HA_tracking',
    question: 'Comment intégrer le suivi du cycle dans son quotidien ?',
    answer: 'Noter ses sensations aide à mieux comprendre les changements du corps.',
    keywords: ['suivi', 'noter'],
    disclaimer: false,
  },
  {
    id: 'HA_32',
    category: 'habits_organization',
    subCategory: 'HA_planning',
    question: 'Comment gérer les journées chargées pendant les règles ?',
    answer: 'Planifier moins d’activités et accepter de ne pas tout faire est parfois nécessaire.',
    keywords: ['chargee', 'travail'],
    disclaimer: false,
  },
  {
    id: 'HA_33',
    category: 'habits_organization',
    subCategory: 'HA_rest',
    question: 'Comment mieux vivre les règles la nuit ?',
    answer: 'Choisir des protections adaptées et privilégier le confort peut améliorer le repos.',
    keywords: ['nuit', 'dormir'],
    disclaimer: false,
  },
  {
    id: 'HA_34',
    category: 'habits_organization',
    subCategory: 'HA_selfcare',
    question: 'Comment respecter son corps sans se sentir limitée ?',
    answer: 'Adapter ses activités sans se juger permet de garder un équilibre.',
    keywords: ['respecter', 'corps'],
    disclaimer: false,
  },
  {
    id: 'HA_35',
    category: 'habits_organization',
    subCategory: 'HA_social',
    question: 'Comment expliquer son besoin de repos à son entourage ?',
    answer: 'Exprimer simplement ce que l’on ressent aide à être mieux comprise.',
    keywords: ['expliquer', 'famille', 'entourage'],
    disclaimer: false,
  },
  {
    id: 'HA_36',
    category: 'habits_organization',
    subCategory: 'HA_emotional',
    question: 'Comment éviter la culpabilité liée à la fatigue menstruelle ?',
    answer: 'La fatigue fait partie des réactions normales du corps et mérite d’être respectée.',
    keywords: ['culpabilite', 'fatigue'],
    disclaimer: false,
  },
  {
    id: 'HA_37',
    category: 'habits_organization',
    subCategory: 'HA_energy',
    question: 'Comment retrouver de l’énergie après les règles ?',
    answer:
      'Une fois le corps rééquilibré, reprendre progressivement ses activités aide à retrouver la vitalité.',
    keywords: ['retrouver', 'energie'],
    disclaimer: false,
  },
  {
    id: 'HA_38',
    category: 'habits_organization',
    subCategory: 'HA_general',
    question: 'Comment utiliser Nye Cyclea au quotidien ?',
    answer:
      'Nye Cyclea aide à suivre le cycle et à mieux comprendre les besoins du corps, même hors connexion.',
    keywords: ['utiliser', 'nye'],
    disclaimer: false,
  },
  {
    id: 'HA_39',
    category: 'habits_organization',
    subCategory: 'HA_general',
    question: 'Comment construire une routine adaptée à son cycle ?',
    answer: 'Observer son cycle permet d’ajuster progressivement ses habitudes.',
    keywords: ['routine', 'habitudes'],
    disclaimer: false,
  },
  {
    id: 'HA_40',
    category: 'habits_organization',
    subCategory: 'HA_general',
    question: 'Pourquoi le bien-être passe par l’écoute de son cycle ?',
    answer: 'Le cycle donne des indications précieuses sur les besoins du corps à chaque étape.',
    keywords: ['coute', 'cycle'],
    disclaimer: false,
  },

  // 🚨 AL. SITUATIONS SENSIBLES & QUAND CONSULTER (AL_01 to AL_40)
  {
    id: 'AL_01',
    category: 'alert_consultation',
    subCategory: 'AL_pain',
    question: 'Quand faut-il consulter si les règles sont très douloureuses ?',
    answer:
      'Lorsque la douleur empêche de mener les activités quotidiennes ou dure plusieurs jours, il est important de consulter un professionnel de santé.',
    keywords: ['consulter', 'douleurs', 'tres'],
    disclaimer: true,
  },
  {
    id: 'AL_02',
    category: 'alert_consultation',
    subCategory: 'AL_bleeding',
    question: 'Quand des règles très abondantes deviennent-elles préoccupantes ?',
    answer:
      'Des règles très abondantes, surtout si elles provoquent fatigue intense ou vertiges, méritent une consultation.',
    keywords: ['abondantes', 'preoccupantes'],
    disclaimer: true,
  },
  {
    id: 'AL_03',
    category: 'alert_consultation',
    subCategory: 'AL_duration',
    question: 'Que faire si les règles durent plus longtemps que d’habitude ?',
    answer:
      'Un changement important et répété de la durée des règles doit être évalué par un professionnel de santé.',
    keywords: ['longtemps', 'duree'],
    disclaimer: true,
  },
  {
    id: 'AL_04',
    category: 'alert_consultation',
    subCategory: 'AL_irregularity',
    question: 'Quand l’absence de règles devient-elle inquiétante ?',
    answer:
      'Une absence de règles sur plusieurs mois, sans raison évidente, nécessite un avis médical.',
    keywords: ['absence', 'inquietante'],
    disclaimer: true,
  },
  {
    id: 'AL_05',
    category: 'alert_consultation',
    subCategory: 'AL_pain',
    question: 'Quand faut-il consulter en cas de douleurs inhabituelles en dehors des règles ?',
    answer:
      'Des douleurs persistantes en dehors des règles peuvent indiquer un problème nécessitant un suivi médical.',
    keywords: ['douleurs', 'dehors', 'regles'],
    disclaimer: true,
  },
  {
    id: 'AL_06',
    category: 'alert_consultation',
    subCategory: 'AL_bleeding',
    question: 'Que signifie un saignement en dehors des règles ?',
    answer:
      'Des saignements en dehors des règles peuvent avoir plusieurs causes et doivent être discutés avec un professionnel.',
    keywords: ['saignement', 'dehors'],
    disclaimer: true,
  },
  {
    id: 'AL_07',
    category: 'alert_consultation',
    subCategory: 'AL_cycle',
    question: 'Quand faut-il s’inquiéter d’un changement soudain du cycle ?',
    answer: 'Un changement brutal et durable du cycle peut nécessiter un avis médical.',
    keywords: ['changement', 'soudain', 'cycle'],
    disclaimer: true,
  },
  {
    id: 'AL_08',
    category: 'alert_consultation',
    subCategory: 'AL_symptoms',
    question: 'Que faire si les règles sont accompagnées de fièvre ?',
    answer:
      'La fièvre associée aux règles n’est pas habituelle et doit conduire à une consultation.',
    keywords: ['fievre', 'regles'],
    disclaimer: true,
  },
  {
    id: 'AL_09',
    category: 'alert_consultation',
    subCategory: 'AL_symptoms',
    question: 'Quand consulter en cas de vertiges fréquents pendant les règles ?',
    answer:
      'Des vertiges répétés peuvent être liés à une perte de sang importante et doivent être évalués.',
    keywords: ['vertiges', 'frequents'],
    disclaimer: true,
  },
  {
    id: 'AL_10',
    category: 'alert_consultation',
    subCategory: 'AL_pain',
    question: 'Que faire si les douleurs ne sont pas soulagées par le repos ?',
    answer:
      'Si les douleurs persistent malgré le repos et les mesures simples, il est important de consulter.',
    keywords: ['douleurs', 'soulagees'],
    disclaimer: true,
  },
  {
    id: 'AL_11',
    category: 'alert_consultation',
    subCategory: 'AL_symptoms',
    question: 'Quand les maux de tête deviennent-ils préoccupants ?',
    answer:
      'Des maux de tête intenses ou inhabituels, surtout s’ils sont nouveaux, doivent être signalés à un professionnel.',
    keywords: ['maux', 'tete', 'intenses'],
    disclaimer: true,
  },
  {
    id: 'AL_12',
    category: 'alert_consultation',
    subCategory: 'AL_fatigue',
    question: 'Que faire en cas de fatigue extrême pendant le cycle ?',
    answer:
      'Une fatigue intense et persistante peut être le signe d’un déséquilibre et nécessite un suivi médical.',
    keywords: ['fatigue', 'extreme'],
    disclaimer: true,
  },
  {
    id: 'AL_13',
    category: 'alert_consultation',
    subCategory: 'AL_symptoms',
    question: 'Quand consulter pour des nausées importantes liées au cycle ?',
    answer:
      'Des nausées sévères ou prolongées doivent être discutées avec un professionnel de santé.',
    keywords: ['nausees', 'importantes'],
    disclaimer: true,
  },
  {
    id: 'AL_14',
    category: 'alert_consultation',
    subCategory: 'AL_pain',
    question: 'Que faire si les règles sont soudainement très douloureuses ?',
    answer:
      'Un changement brutal de la douleur mérite une consultation pour en comprendre la cause.',
    keywords: ['soudainement', 'douloureuses'],
    disclaimer: true,
  },
  {
    id: 'AL_15',
    category: 'alert_consultation',
    subCategory: 'AL_symptoms',
    question: 'Quand s’inquiéter d’un gonflement anormal ?',
    answer:
      'Un gonflement important, douloureux ou inhabituel doit être évalué par un professionnel.',
    keywords: ['gonflement', 'anormal'],
    disclaimer: true,
  },
  {
    id: 'AL_16',
    category: 'alert_consultation',
    subCategory: 'AL_pain',
    question: 'Que faire si les douleurs s’aggravent avec le temps ?',
    answer: 'Une aggravation progressive des symptômes nécessite un avis médical.',
    keywords: ['aggravent', 'temps'],
    disclaimer: true,
  },
  {
    id: 'AL_17',
    category: 'alert_consultation',
    subCategory: 'AL_bleeding',
    question: 'Quand faut-il consulter en cas de pertes inhabituelles ?',
    answer:
      'Des pertes avec une odeur forte, une couleur inhabituelle ou associées à des douleurs doivent être examinées.',
    keywords: ['pertes', 'inhabituelles'],
    disclaimer: true,
  },
  {
    id: 'AL_18',
    category: 'alert_consultation',
    subCategory: 'AL_symptoms',
    question: 'Que faire si les règles provoquent des malaises répétés ?',
    answer: 'Les malaises répétés ne sont pas normaux et nécessitent une consultation.',
    keywords: ['malaises', 'repetes'],
    disclaimer: true,
  },
  {
    id: 'AL_19',
    category: 'alert_consultation',
    subCategory: 'AL_pain',
    question: 'Quand consulter pour des douleurs pendant les rapports ?',
    answer:
      'Des douleurs régulières pendant les rapports doivent être signalées à un professionnel de santé.',
    keywords: ['douleurs', 'rapports'],
    disclaimer: true,
  },
  {
    id: 'AL_20',
    category: 'alert_consultation',
    subCategory: 'AL_irregularity',
    question: 'Que faire si les règles deviennent très irrégulières ?',
    answer: 'Une irrégularité importante et persistante du cycle doit être évaluée.',
    keywords: ['irregulieres', 'tres'],
    disclaimer: true,
  },
  {
    id: 'AL_21',
    category: 'alert_consultation',
    subCategory: 'AL_weight',
    question: 'Quand s’inquiéter d’une perte de poids ou de prise de poids rapide ?',
    answer:
      'Des changements rapides et inexpliqués du poids peuvent influencer le cycle et nécessitent un suivi.',
    keywords: ['poids', 'rapide'],
    disclaimer: true,
  },
  {
    id: 'AL_22',
    category: 'alert_consultation',
    subCategory: 'AL_cycle',
    question: 'Que faire si le cycle s’arrête après une maladie ou un stress intense ?',
    answer: 'Si le cycle ne reprend pas après plusieurs mois, un avis médical est recommandé.',
    keywords: ['arret', 'maladie', 'stress'],
    disclaimer: true,
  },
  {
    id: 'AL_23',
    category: 'alert_consultation',
    subCategory: 'AL_pain',
    question: 'Quand faut-il consulter en cas de douleurs pelviennes constantes ?',
    answer: 'Des douleurs pelviennes persistantes doivent être examinées par un professionnel.',
    keywords: ['pelviennes', 'constantes'],
    disclaimer: true,
  },
  {
    id: 'AL_24',
    category: 'alert_consultation',
    subCategory: 'AL_symptoms',
    question: 'Que faire si les règles sont accompagnées de palpitations ?',
    answer:
      'Les palpitations associées à des règles abondantes ou à une grande fatigue nécessitent une consultation.',
    keywords: ['palpitations', 'coeur'],
    disclaimer: true,
  },
  {
    id: 'AL_25',
    category: 'alert_consultation',
    subCategory: 'AL_bleeding',
    question: 'Quand consulter si les protections sont saturées très rapidement ?',
    answer:
      'Un besoin de changer les protections très fréquemment est un signal important à ne pas ignorer.',
    keywords: ['protections', 'saturees'],
    disclaimer: true,
  },
  {
    id: 'AL_26',
    category: 'alert_consultation',
    subCategory: 'AL_symptoms',
    question: 'Que faire en cas de sensation de malaise général pendant le cycle ?',
    answer: 'Un malaise général persistant doit être évalué par un professionnel.',
    keywords: ['malaise', 'general'],
    disclaimer: true,
  },
  {
    id: 'AL_27',
    category: 'alert_consultation',
    subCategory: 'AL_pain',
    question: 'Quand faut-il s’inquiéter de douleurs soudaines et intenses ?',
    answer: 'Des douleurs soudaines et très intenses nécessitent une consultation rapide.',
    keywords: ['soudaines', 'intenses'],
    disclaimer: true,
  },
  {
    id: 'AL_28',
    category: 'alert_consultation',
    subCategory: 'AL_symptoms',
    question: 'Que faire si les règles sont accompagnées de vomissements répétés ?',
    answer:
      'Les vomissements fréquents ne sont pas habituels et doivent être discutés avec un professionnel.',
    keywords: ['vomissements', 'repetes'],
    disclaimer: true,
  },
  {
    id: 'AL_29',
    category: 'alert_consultation',
    subCategory: 'AL_sleep',
    question: 'Quand consulter pour des troubles du sommeil sévères ?',
    answer:
      'Des troubles importants du sommeil qui durent plusieurs cycles méritent un avis médical.',
    keywords: ['troubles', 'sommeil'],
    disclaimer: true,
  },
  {
    id: 'AL_30',
    category: 'alert_consultation',
    subCategory: 'AL_cycle',
    question: 'Que faire si le corps semble ne plus suivre le rythme habituel ?',
    answer: 'Un sentiment de déséquilibre durable doit être évalué par un professionnel.',
    keywords: ['rythme', 'habituel'],
    disclaimer: true,
  },
  {
    id: 'AL_31',
    category: 'alert_consultation',
    subCategory: 'AL_cycle',
    question: 'Quand faut-il consulter après l’arrêt d’une contraception ?',
    answer: 'Si le cycle ne se régule pas après plusieurs mois, un suivi médical est conseillé.',
    keywords: ['arret', 'contraception'],
    disclaimer: true,
  },
  {
    id: 'AL_32',
    category: 'alert_consultation',
    subCategory: 'AL_general',
    question: 'Que faire si les symptômes deviennent difficiles à supporter ?',
    answer: 'Lorsque les symptômes impactent fortement la qualité de vie, consulter est important.',
    keywords: ['difficiles', 'supporter'],
    disclaimer: true,
  },
  {
    id: 'AL_33',
    category: 'alert_consultation',
    subCategory: 'AL_general',
    question: 'Quand faut-il demander de l’aide extérieure ?',
    answer:
      'Dès que l’on se sent dépassée ou inquiète, il est utile de demander un avis professionnel.',
    keywords: ['aide', 'exterieure'],
    disclaimer: true,
  },
  {
    id: 'AL_34',
    category: 'alert_consultation',
    subCategory: 'AL_general',
    question: 'Pourquoi est-il important de ne pas ignorer les signaux du corps ?',
    answer: 'Le corps envoie des messages qui aident à prévenir des problèmes plus sérieux.',
    keywords: ['ignorer', 'signaux'],
    disclaimer: true,
  },
  {
    id: 'AL_35',
    category: 'alert_consultation',
    subCategory: 'AL_general',
    question: 'Comment parler de ses symptômes à un professionnel de santé ?',
    answer:
      'Décrire les symptômes, leur fréquence et leur impact sur le quotidien aide à une meilleure prise en charge.',
    keywords: ['parler', 'professionnel'],
    disclaimer: true,
  },
  {
    id: 'AL_36',
    category: 'alert_consultation',
    subCategory: 'AL_general',
    question: 'Pourquoi Nye Cyclea n’établit pas de diagnostic ?',
    answer:
      'Nye Cyclea est une application éducative qui oriente, mais seul un professionnel peut poser un diagnostic.',
    keywords: ['diagnostic', 'nye'],
    disclaimer: true,
  },
  {
    id: 'AL_37',
    category: 'alert_consultation',
    subCategory: 'AL_general',
    question: 'Comment Nye Cyclea aide à reconnaître les situations sensibles ?',
    answer:
      'L’application aide à identifier les changements inhabituels et à encourager une consultation lorsque nécessaire.',
    keywords: ['reconnaitre', 'sensibles'],
    disclaimer: true,
  },
  {
    id: 'AL_38',
    category: 'alert_consultation',
    subCategory: 'AL_general',
    question: 'Pourquoi consulter tôt est important ?',
    answer:
      'Consulter tôt permet souvent d’éviter des complications et d’obtenir des solutions adaptées.',
    keywords: ['consulter', 'tot'],
    disclaimer: true,
  },
  {
    id: 'AL_39',
    category: 'alert_consultation',
    subCategory: 'AL_mental',
    question: 'Comment garder une attitude calme face aux symptômes inquiétants ?',
    answer:
      'S’informer, observer son corps et consulter un professionnel aide à réduire l’anxiété.',
    keywords: ['calme', 'inquietants'],
    disclaimer: true,
  },
  {
    id: 'AL_40',
    category: 'alert_consultation',
    subCategory: 'AL_role',
    question: 'Quel est le rôle de Nye Cyclea dans les situations sensibles ?',
    answer:
      'Nye Cyclea informe, rassure et oriente vers un professionnel lorsque les signes sortent de l’ordinaire.',
    keywords: ['role', 'sensibles'],
    disclaimer: true,
  },
];
