/// <reference lib="WebWorker" />

import {
  precacheAndRoute,
  cleanupOutdatedCaches,
  createHandlerBoundToURL,
} from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { PredictionService } from './services/predictionService';
import { StorageService } from './services/storageService';

declare let self: ServiceWorkerGlobalScope & { __WB_MANIFEST: any[] };

// Cleanup old caches
cleanupOutdatedCaches();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Cache Google Fonts - Stylesheets
registerRoute(
  /^https:\/\/fonts\.googleapis\.com\/.*/i,
  new StaleWhileRevalidate({
    cacheName: 'google-fonts-stylesheets',
  })
);

// Cache Google Fonts - Webfont files
registerRoute(
  /^https:\/\/fonts\.gstatic\.com\/.*/i,
  new CacheFirst({
    cacheName: 'google-fonts-webfonts',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxAgeSeconds: 60 * 60 * 24 * 365,
        maxEntries: 30,
      }),
    ],
  })
);

// Handle navigation requests (SPA)
// Using index.html without leading slash to match manifest keys
try {
  const navigationHandler = async (params: any) => {
    try {
      return await createHandlerBoundToURL('index.html')(params);
    } catch (error) {
      console.error('[SW] Navigation handler failed, falling back to network if possible:', error);
      return fetch(params.event.request);
    }
  };

  const navigationRoute = new NavigationRoute(navigationHandler, {
    // Exclude URLs starting with /__ (like Firebase auth) and common backend paths
    denylist: [/^\/__/, /^\/api/],
  });
  registerRoute(navigationRoute);
} catch (error) {
  console.error('[SW] Navigation route registration failed:', error);
}

// Immediate activation
self.addEventListener('install', (event) => event.waitUntil(self.skipWaiting()));
self.addEventListener('activate', (event) => event.waitUntil(clientsClaim()));

// Listen for Periodic Background Sync
self.addEventListener('periodicsync' as any, (event: any) => {
  if (event.tag === 'daily-cycle-update') {
    event.waitUntil(checkAndNotify());
  }
});

// Listener for manual triggers or fallback from main thread
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'CHECK_NOTIFICATIONS') {
    console.log('[SW] Message received: CHECK_NOTIFICATIONS');
    event.waitUntil(checkAndNotify());
  }
  if (event.data && event.data.type === 'START_SCHEDULER') {
    console.log('[SW] Scheduler start requested');
  }
});

// Check for notifications on SW activation
self.addEventListener('activate', (event) => {
  console.log('[SW] Service Worker activating and taking control...');
  event.waitUntil(checkAndNotify());
});

async function checkAndNotify() {
  try {
    console.log('[SW] Checking notifications...');

    const cycles = await StorageService.getCyclesAsync();
    if (cycles.length === 0) {
      console.log('[SW] No cycles found');
      return;
    }

    const settings = await StorageService.getSettingsAsync();
    if (!settings.notificationsOn) {
      console.log('[SW] Notifications disabled');
      return;
    }

    const phase = PredictionService.getCurrentPhase(cycles);
    const prediction = PredictionService.predictNextCycle(cycles);

    // Get local date in ISO format
    const todayDate = new Date();
    const todayStr = `${todayDate.getFullYear()}-${String(todayDate.getMonth() + 1).padStart(2, '0')}-${String(todayDate.getDate()).padStart(2, '0')}`;

    // Priority 1: Predicted Period
    const daysUntilPeriod = prediction?.predictedStart
      ? daysBetween(todayStr, prediction.predictedStart)
      : 100;

    let title = '';
    let body = '';
    let shouldNotify = true;

    if (daysUntilPeriod <= 3 && daysUntilPeriod >= 0) {
      title =
        daysUntilPeriod === 0
          ? "Vos règles commencent aujourd'hui"
          : `Règles prévues dans ${daysUntilPeriod} jour${daysUntilPeriod > 1 ? 's' : ''}`;
      body = 'Préparez-vous, votre nouveau cycle commence bientôt. 🌸';
    } else if (phase.phase === 'ovulation') {
      title = `Jour ${phase.dayOfCycle} : Ovulation`;
      body = "Pic de fertilité aujourd'hui ! 🥚✨";
    } else {
      const phaseNames: Record<string, string> = {
        menstruation: 'Règles',
        follicular: 'Phase folliculaire',
        ovulation: 'Ovulation',
        luteal: 'Phase lutéale',
      };

      const phaseName = phaseNames[phase.phase] || 'Cycle';
      title = `Jour ${phase.dayOfCycle} : ${phaseName}`;

      if (phase.phase === 'menstruation') body = 'Prenez soin de vous pendant cette phase. ☕';
      else if (phase.phase === 'follicular') body = 'Votre énergie augmente progressivement. 💪';
      else if (phase.phase === 'luteal') body = "C'est le moment de ralentir et de se relaxer. 🧘";
      else {
        shouldNotify = false;
      }
    }

    if (shouldNotify) {
      console.log('[SW] Sending notification:', title);

      await self.registration.showNotification(title, {
        body,
        icon: '/icons/pwa-192x192.png',
        badge: '/icons/pwa-192x192.png',
        tag: 'cycle-daily-update',
        renotify: true,
        data: { url: '/' },
        vibrate: [100, 50, 100],
      } as any);
    }
  } catch (error) {
    console.error('[SW] Notification error:', error);
  }
}

function daysBetween(d1: string, d2: string): number {
  const one = new Date(d1);
  const two = new Date(d2);
  const diff = two.getTime() - one.getTime();
  return Math.ceil(diff / (1000 * 3600 * 24));
}

// Handle notification clicks
self.addEventListener('notificationclick', (event: any) => {
  event.notification.close();
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList: any) => {
      if (clientList.length > 0) {
        return clientList[0].focus();
      }
      return self.clients.openWindow('/');
    })
  );
});
