/// <reference lib="WebWorker" />

import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';
import { PredictionService } from './services/predictionService';
import { StorageService } from './services/storageService';

const sw = self as unknown as ServiceWorkerGlobalScope & { __WB_MANIFEST: any };

// @ts-ignore - This is required by workbox injectManifest
self.__WB_MANIFEST = sw.__WB_MANIFEST;

// Precache all assets generated by Vite
precacheAndRoute(sw.__WB_MANIFEST);
cleanupOutdatedCaches();

sw.addEventListener('install', (event: any) => event.waitUntil(sw.skipWaiting()));
sw.addEventListener('activate', (event: any) => event.waitUntil(clientsClaim()));

// Listen for Periodic Background Sync
sw.addEventListener('periodicsync' as any, (event: any) => {
  if (event.tag === 'daily-cycle-update') {
    event.waitUntil(checkAndNotify());
  }
});

// Listener for manual triggers or fallback from main thread
sw.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'CHECK_NOTIFICATIONS') {
    console.log('[SW] Message received: CHECK_NOTIFICATIONS');
    event.waitUntil(checkAndNotify());
  }
});

// Enhanced: Check for notifications on SW activation
sw.addEventListener('activate', (event: any) => {
  console.log('[SW] Service Worker activating...');
  event.waitUntil(
    Promise.all([
      clientsClaim(),
      // Check notifications immediately when SW activates
      checkAndNotify(),
    ])
  );
});

async function checkAndNotify() {
  try {
    console.log('[SW] Checking notifications...');

    const cycles = await StorageService.getCyclesAsync();
    if (cycles.length === 0) {
      console.log('[SW] No cycles found');
      return;
    }

    const settings = await StorageService.getSettingsAsync();
    if (!settings.notificationsOn) {
      console.log('[SW] Notifications disabled');
      return;
    }

    const phase = PredictionService.getCurrentPhase(cycles);
    const prediction = PredictionService.predictNextCycle(cycles);

    // Get local date in ISO format
    const todayDate = new Date();
    const todayStr = `${todayDate.getFullYear()}-${String(todayDate.getMonth() + 1).padStart(2, '0')}-${String(todayDate.getDate()).padStart(2, '0')}`;

    // Check if we already sent notification today - Removed localStorage bug. 
    // We rely on the 'renotify: false' or same 'tag' to prevent duplicates if needed.
    // In a real app we would use IndexedDB here.

    // Priority 1: Predicted Period
    const daysUntilPeriod = prediction?.predictedStart
      ? daysBetween(todayStr, prediction.predictedStart)
      : 100;

    let title = '';
    let body = '';
    let shouldNotify = true;

    if (daysUntilPeriod <= 3 && daysUntilPeriod >= 0) {
      title =
        daysUntilPeriod === 0
          ? "Vos règles commencent aujourd'hui"
          : `Règles prévues dans ${daysUntilPeriod} jour${daysUntilPeriod > 1 ? 's' : ''}`;
      body = 'Préparez-vous, votre nouveau cycle commence bientôt. 🌸';
    } else if (phase.phase === 'ovulation') {
      title = `Jour ${phase.dayOfCycle} : Ovulation`;
      body = "Pic de fertilité aujourd'hui ! 🥚✨";
    } else {
      // Standard daily phase update
      const phaseNames: Record<string, string> = {
        menstruation: 'Règles',
        follicular: 'Phase folliculaire',
        ovulation: 'Ovulation',
        luteal: 'Phase lutéale',
      };

      const phaseName = phaseNames[phase.phase] || 'Cycle';
      title = `Jour ${phase.dayOfCycle} : ${phaseName}`;

      if (phase.phase === 'menstruation') body = 'Prenez soin de vous pendant cette phase. ☕';
      else if (phase.phase === 'follicular') body = 'Votre énergie augmente progressivement. 💪';
      else if (phase.phase === 'luteal') body = "C'est le moment de ralentir et de se relaxer. 🧘";
      else {
        // Unknown or too long - maybe don't spam?
        shouldNotify = false;
      }
    }

    if (shouldNotify) {
      console.log('[SW] Sending notification:', title);

      await sw.registration.showNotification(title, {
        body,
        icon: '/icons/pwa-192x192.png',
        badge: '/icons/pwa-192x192.png',
        tag: 'cycle-daily-update',
        renotify: true,
        data: { url: '/' },
        requireInteraction: daysUntilPeriod <= 1, // Require interaction for important notifications
        vibrate: [100, 50, 100],
      } as any);

      // Mark that we sent notification today - Removed localStorage bug.
    }
  } catch (error) {
    console.error('[SW] Notification error:', error);
  }
}

function daysBetween(d1: string, d2: string): number {
  const one = new Date(d1);
  const two = new Date(d2);
  const diff = two.getTime() - one.getTime();
  return Math.ceil(diff / (1000 * 3600 * 24));
}

// Handle notification clicks
sw.addEventListener('notificationclick', (event: any) => {
  event.notification.close();
  event.waitUntil(
    sw.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList: any) => {
      if (clientList.length > 0) {
        return clientList[0].focus();
      }
      return sw.clients.openWindow('/');
    })
  );
});
